
tasks:
  - name: Install Laravel Sail
    init: |
      curl -s https://laravel.build/example-app | bash
      echo "Laravel Installation completed, setting up..."
      gp sync-done install
    command: | 
      cd example-app
      vendor/bin/sail up

  - name: Migrate Databases
    command: |
      gp sync-await install
      sleep 10
      cd example-app
      vendor/bin/sail artisan migrate

ports:
  - name: Laravel Webserver
    description: Laravel Websserver
    port: 80
    onOpen: open-preview