
tasks:
  - name: Install Laravel Sail
    init: |
      curl -s https://laravel.build/example-app | bash
      echo "Laravel Installation completed, setting up..."
    command: | 
      cd example-app
      vendor/bin/sail up
      sleep 5
      vendor/bin/sail artisan migrate

  - name: Setup alias
    command: alias sail='sh $([ -f sail ] && echo sail || echo vendor/bin/sail)'

ports:
  - name: Laravel Webserver
    description: Laravel Websserver
    port: 80
    onOpen: open-preview